name: process

on:
  workflow_dispatch:

jobs:
  process:
    runs-on: ubuntu-latest
    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - uses: actions/checkout@v2
   
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - name: Install ffmpeg
      run: |
        sudo apt-get update 
        sudo apt-get install ffmpeg

    - name: Install Dependencies
      run: npm install

    - name: Run Roku tests
      run: npm run process