name: test

on:
  push:
    branches:
      - '**'
    paths:
      - '**.js'
      - '**/package.json'
      - '**.yml'
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
   
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Run Unit Tests
      run: npm run test-ci

    - name: Publish Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: test-results.xml